server:
  port: 8080

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://stakeholder-mysql:3306/stakeholder_db}
    username: ${MYSQL_USER:stk_user}
    password: ${MYSQL_PASS:stk_pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true